allow disabling auto updates
vsc-eco/vsc-deployment pull request #5
Opened 2024-05-10 16:05 UTC by Pl8tinium

2024-05-10 16:37 UTC, Geo25rey requested changes
I think auto update should be the default and having the ability to opt-out is fine, but I think the risk of being excluded from the network if your node is out of date should be mentioned.

2024-05-10 16:49 UTC, Geo25rey commented
You should be able to use the `enabled` flag on the watchtower container combined with the `.env` file accessible in the `docker-compose.yml` https://docs.docker.com/compose/environment-variables/env-file/

2024-05-10 21:40 UTC, Pl8tinium commented
https://containrrr.dev/watchtower/container-selection/

aah i missed that 🙂

2024-05-11 01:16 UTC, Geo25rey approved these changes

2024-05-11 01:16 UTC, Geo25rey commented on docker-compose.yml
>      command: --interval 3600 --cleanup
I thought you were gonna add the `enabled` flag to the `watchtower` Docker Compose service defined in `docker-compose.yml`, but this works too. It's probably a good idea to enable the whitelist command option to watchtower like this, too. 
https://containrrr.dev/watchtower/arguments/#filter_by_enable_label

As long as you tested the `.env` `AUTO_UPDATE` value locally, LGTM

```suggestion
    command: --label-enable --interval 3600 --cleanup
```

2024-05-11 13:45 UTC, Pl8tinium commented
![image](https://github.com/vsc-eco/vsc-deployment/assets/50824212/857afcbf-abda-4c31-a395-620000557b72)

tested locally, works

2024-05-11 13:47 UTC, merged